import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Posts",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={``}>

      <div className="relative flex min-h-screen justify-center mx-auto flex-col max-w-5xl  bg-background">
        {children}
      </div>
    </div>
  );
}
